<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7d6bb85be15a6d5f249fe19bbb71fd2c
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7d6bb85be15a6d5f249fe19bbb71fd2c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7d6bb85be15a6d5f249fe19bbb71fd2c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
